version: '3'

services:
  db:
    container_name: django-test-db
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=mmlcalculator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      #docker.for.win.localhost
    

    

  web:
    container_name: mlkit
    build: .
    command: python manage.py makemigrations
    command: python dbinit.py
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db


