version: '3'

services:
  db:
    container_name: django-test-db
    image: postgres:alpine
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=mmlcalculator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Tokyo

    

    

  web:
    #create from python:3.8-alpine
    container_name: mlkit_slim
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata dbinit.json && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db


