# Generated by Django 3.1 on 2020-09-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_auto_20200829_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='selectedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='selectedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdl', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
            ],
        ),
    ]
