# Generated by Django 3.1 on 2020-09-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_selecteddata_selectedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('loss', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='selecteddata',
            name='data',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
