# Generated by Django 3.1 on 2020-08-29 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technique',
            new_name='MlModel',
        ),
        migrations.RenameField(
            model_name='mlmodel',
            old_name='tech',
            new_name='mdl',
        ),
    ]
