# Generated by Django 3.1 on 2020-09-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_auto_20200910_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='loss',
        ),
        migrations.AddField(
            model_name='results',
            name='loss_test',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='results',
            name='loss_train',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
