# Generated by Django 3.1.1 on 2020-10-02 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0005_auto_20200916_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='NN_layers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer1', models.PositiveSmallIntegerField(default=64, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('layer2', models.PositiveSmallIntegerField(default=64, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
            ],
        ),
    ]
