# Generated by Django 3.1.1 on 2020-10-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_results_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nn_layers',
            name='layer1',
            field=models.PositiveSmallIntegerField(default=64),
        ),
        migrations.AlterField(
            model_name='nn_layers',
            name='layer2',
            field=models.PositiveSmallIntegerField(default=64),
        ),
    ]
